# [START runtime]
runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: cool_school-backend:us-central1:cool_school-db

runtime_config:
  python_version: 3
# [END runtime]